#!/usr/bin/env python3

"""
SSHD authorized_keys file handling utility
"""


import os
import sys
from typing import Final

from dynacli import main

cwd = os.path.dirname(os.path.realpath(__file__))

__version__: Final[str] = "1.0.0"


search_path = [f'{cwd}/src']
sys.path.extend(search_path)

main(search_path)
